# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

cmake_minimum_required(VERSION 3.14)
project(reverie_clean_call_context C ASM)
find_package(DynamoRIO REQUIRED)
add_library(clean_call_context_client SHARED client.c)
configure_DynamoRIO_client(clean_call_context_client)
use_DynamoRIO_extension(clean_call_context_client drmgr)
use_DynamoRIO_extension(clean_call_context_client drreg)
target_compile_options(clean_call_context_client PRIVATE -Werror=implicit-function-declaration)
add_executable(clean_call_context_guest guest.c probe.S)
target_link_options(clean_call_context_guest PRIVATE -rdynamic)
target_link_libraries(clean_call_context_guest PRIVATE pthread)
