[package]
name = "reverie-dbt"
description = "Dynamic binary instrumentation (DBT) execution backend for the Reverie framework."
version = "0.2.0"
authors = ["Meta Platforms"]
edition = "2024"
repository = "https://github.com/facebookexperimental/reverie"
license = "BSD-2-Clause AND BSD-3-Clause AND LGPL-2.1-only AND BSD-4-Clause"
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["prototype-runtime"]
prototype-runtime = []

[dependencies]
bincode = { version = "2", features = ["serde"] }
libc = "0.2.186"
reverie = { version = "0.2.0", path = "../reverie", package = "reverie-core" }
reverie-memory = { version = "0.2.0", path = "../reverie-memory" }
reverie-rpc-transport = { version = "0.2.0", path = "../reverie-rpc-transport" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["alloc"] }
tempfile = "3.27.0"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "net", "time"] }
tracing = "0.1.41"

[build-dependencies]
sha2 = "0.10.9"

[dev-dependencies]
sha2 = "0.10.9"
